### PR TITLE
Removed status checking

### PR DESCRIPTION
**Pull request by formatBCE**
Improved speed of command execution

### CODE REVIEW

**Comment by rospogrigio** [comment]
OK how should I install the ESPHome? Sorry but I'm no expert with this and I don't want to mess up things...

**Comment by rospogrigio** [comment]
OK I managed to switch to ESPHome and install this PR, everything seems to be working, let me try it for a bit and I'll provide some feedback. Thank you again!

**Comment by jcustenborder** [comment]
@formatBCE @rospogrigio What is the status of this PR? Is this the direction the project is heading?

**Comment by formatBCE** [comment]
> @formatBCE @rospogrigio What is the status of this PR? Is this the direction the project is heading?

I use this since writing on M300. No problems/sticks at all.
Don't know if @rospogrigio will merge it though - looks like it doesn't work this good for M500.

**Pull request merged**
