### PR TITLE
airbnk_mqtt_reload_fix

### PR DESCRIPTION
**Pull request by TheDescender**
Rewrite of async_unload_entry function to be compatible with Python V3.11 to once again support integration reloading without HA restart.

### CODE REVIEW

**Review by formatBCE — APPROVED** [review]

**Comment by rospogrigio** [comment]
Looks like the reload service is working again. Please merge back from my master branch and confirm that now everything is stable on your side, then I'll merge this and release.

**Comment by TheDescender** [comment]
Ok Ignore the other PR I made by accident, like I said first time using GitHub. After merge back from master and pulling my branch into HA from HACS, functionality seems to be good. Code in changed file also looked the same as before merging back from master, so I imagine it's good.

**Comment by rospogrigio** [comment]
OK my proposal is: test it for a couple of days, and check if you still encounter the issues you were reporting, and also whether in those case if you are able to recover by reloading integration. If everything seems to work fine, post a feedback here and I'll merge everything and publish a new release.
Thank you for your contribution 😉

**Comment by rospogrigio** [comment]
So? Is it ok to merge?

**Comment by TheDescender** [comment]
Yep. So far I've not run into reloading issues and when I get stuck on operating status. This change allows me to restart the integration with an automation. Seems good to merge.

**Review by rospogrigio — APPROVED** [review]

**Pull request merged**
